BEGIN;

TRUNCATE
  bobatier_ratings,
  bobatier_drinks,
  bobatier_shops,
  bobatier_users;

INSERT INTO bobatier_shops (id, shop_name, city, state)
VALUES
  (1, 'Gongcha', 'Houston', 'TX'),
  (2, 'Sharetea', 'Houston' 'TX'),
  (3, 'Kung Fu Tea', 'Houston' 'TX'),
  (4, 'Ding Tea', 'Houston' 'TX'),
  (5, 'The Teahouse', 'Houston' 'TX'),
  (6, 'Bubble Tea House', 'Houston' 'TX'),
  (7, '7 Leaves Cafe', 'Houston' 'TX'),
  (8, 'Teaholic', 'Houston' 'TX'),
  (9, 'Feng Cha', 'Houston' 'TX'),
  (10, 'BoBa Island', 'Houston' 'TX'),
  (11, 'Kim''s Teahouse', 'Houston' 'TX'),
  (12, 'Teapresso Bar', 'Houston' 'TX'),
  (13, 'Tea Top', 'Houston' 'TX'),
  (14, 'Tiger Sugar', 'Houston' 'TX'),
  (15, 'Nu Ice & Drinks', 'Houston' 'TX'),
  (16, 'Yumcha', 'Houston' 'TX'),
  (17, 'Boba City', 'Houston' 'TX'),
  (18, 'The Boba Spot', 'Houston' 'TX'),
  (19, 'I Heart Boba', 'Houston' 'TX'),
  (20, 'Bobo Tea', 'Houston' 'TX');

INSERT INTO bobatier_drinks (id, drink_name, shop_id)
VALUES
  (101, 'Green Milk Foam Tea', 1),
  (102, 'Black Milk Foam Tea', 1),
  (103, 'Oolong Milk Foam Tea', 1),
  (104, 'Earl Grey Milk Foam Tea', 1),
  (105, 'Wintermelon Milk Foam Tea', 1),
  (106, 'Dirty Brown Sugar Milk Tea', 1),
  (107, 'Milk Tea', 1),
  (108, 'Pearl Milk Tea', 1),
  (109, 'Caramel Milk Tea', 1),
  (110, 'Brown Sugar Milk Tea', 1),
  (111, 'Wintermelon Milk Tea', 1),
  (112, 'Strawberry Milk Tea', 1),
  (113, 'Earl Grey Milk Tea with 3 J''s', 1),
  (114, 'Green Tea', 1),
  (115, 'Hibiscus Green Tea', 1),
  (116, 'Honey Green Tea', 1),
  (117, 'Lychee Oolong', 1),
  (118, 'Lemon Ai-yu White Pearl', 1),
  (119, 'Lemon Wintermelon Basil Seeds', 1),
  (120, 'Taro', 1),
  (121, 'Caramel Chocolate', 1),
  (122, 'Yogurt Drink', 1),
  (201, 'Mango Green Tea', 2),
  (202, 'Wintermelon Lemonade', 2),
  (203, 'Strawberry Tea', 2),
  (204, 'Peach Tea with Aiyu Jelly', 2),
  (205, 'Peach Kiwi Tea with Aiyu Jelly', 2),
  (206, 'Honey Lemonade with Aloe Vera', 2),
  (207, 'Kiwi Fruit Tea with Aiyu Jelly', 2),
  (208, 'Mango & Passion Fruit Tea', 2),
  (209, 'Hawaii Fruit Tea with Aiyu Jelly', 2),
  (210, 'Tropical Fruit Tea', 2),
  (211, 'Passionfruit, Orange and Grapefruit Tea', 2),
  (212, 'Classic Milk Tea', 2),
  (213, 'Honey Milk Tea', 2),
  (214, 'Classic Coffee', 2),
  (215, 'Ginger Milk Tea', 2),
  (216, 'Coffee Milk Tea', 2),
  (217, 'Classic Pearl Milk Tea', 2),
  (218, 'Hokkaido Pearl Milk Tea', 2),
  (219, 'Thai Pearl Milk Tea', 2),
  (220, 'Taro Pearl Milk Tea', 2),
  (221, 'Mango Green Milk Tea', 2),
  (222, 'QQ Happy Family Milk Tea', 2),
  (223, 'Matcha Red Bean Milk Tea', 2),
  (224, 'Lime Mojito', 2),
  (225, 'Mango Mojito', 2),
  (226, 'Peach Mojito', 2),
  (227, 'Strawberry Mojito', 2),
  (301, 'Longan Jujube Tea', 3),
  (302, 'Kung Fu Black Tea', 3),
  (303, 'Kung Fu Green Tea', 3),
  (304, 'Kung Fu Oolong Tea', 3),
  (305, 'Kung Fu Honey Tea', 3),
  (306, 'Honey Black Tea', 3),
  (307, 'Honey Green Tea', 3),
  (308, 'Honey Oolong Tea', 3),
  (309, 'Winter Melon Tea', 3),
  (310, 'Winter Melon Green Tea', 3),
  (311, 'Kung Fu Milk Tea', 3),
  (312, 'Kung Fu Milk Green Tea', 3),
  (313, 'Rosehip Milk Tea', 3),
  (314, 'Coffee Milk Tea', 3),
  (315, 'Taro Milk Tea', 3),
  (316, 'Taro Milk Green Tea', 3),
  (317, 'Honey Milk Tea', 3),
  (318, 'Honey Milk Green Tea', 3),
  (319, 'Thai Milk Tea', 3),
  (320, 'Winter Melon Milk Green Tea', 3),
  (321, 'Oolong Milk Tea', 3),
  (322, 'Honey Oolong Milk Tea', 3),
  (323, 'Coconut Milk Tea', 3),
  (324, 'Almond Milk Tea', 3),
  (325, 'Honey Tea Cap', 3),
  (326, 'Matcha Milk Cap', 3),
  (327, 'Cocoa Cream Wow with Milk Cap', 3),
  (328, 'Jujube Tea Milk Cap', 3),
  (329, 'Sunshine Pineapple Tea Cap', 3),
  (330, 'Winter Melon Tea Cap', 3),
  (401, 'Signature Milk Tea', 4),
  (402, 'Jasmine Green Milk Tea', 4),
  (403, 'Wintermelon Tea', 4),
  (404, 'Strawberry Yakult', 4),
  (405, 'Wintermlon Milk Tea', 4),
  (406, 'Taro Milk Tea', 4),
  (407, 'Matcha Milk Tea', 4),
  (408, 'Hokkaido Oolong Milk Tea', 4),
  (409, 'Lychee Green Tea', 4),
  (410, 'Top Fruit Tea', 4),
  (701, 'Mint Sereno', 7),
  (702, 'Jasmine Milk Tea', 7),
  (703, 'Japanese Matcha Soy Tea', 7),
  (704, 'Vietnamese Coffee', 7),
  (705, 'House Coffee', 7),
  (706, 'Japanese Matcha Tea', 7),
  (707, 'Taro Milk Tea', 7),
  (708, 'Thai Tea', 7),
  (709, 'Sea Cream Jasmine Tea', 7),
  (710, 'Sea Cream Black Coffee', 7),
  (711, 'Herbal Tea', 7),
  (712, 'Strawberry Hibiscus Tea', 7),
  (713, 'Mung Bean Milk Tea', 7),
  (714, 'Sunset Passion', 7),
  (715, 'Assam Milk Tea', 7),
  (716, 'Oolong Milk Tea', 7);

COMMIT;